name: App Build
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Release
        run: |
          gh release create ${{ github.event.inputs.release_tag }} --title "Release ${{ github.event.inputs.release_tag }}" \
          --notes "Action auto release" --draft
        env:
          GH_TOKEN: ${{ github.token }}

  build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      permissions:
        contents: write
      needs: create

      steps:
        # Check-out repository
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: 3.12

        - name: Avoid gh API error
          if: ${{ matrix.os == 'macos-latest' }}
          run: sleep 1000

        - name: Download server
          run: |
            cd src-tauri
            pip install requests
            python download_server.py

        - name: Setup pnpm
          uses: pnpm/action-setup@v4.0.0
          with:
            version: 9

        - name: Install Dependencies
          run: |
            pnpm install

        - name: Install GTK for linux
          if: ${{ matrix.os == 'ubuntu-latest' }}
          run: |
            sudo apt install libwebkit2gtk-4.1-dev \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev
            sudo apt install libgtk-3-dev
            sudo apt install libsoup-3.0-0 libsoup-3.0-dev

        - name: Build
          run: |
            pnpm tauri build

        - name: tree
          continue-on-error: true
          run: |
            tree

        - name: Release Linux
          if: ${{ matrix.os == 'ubuntu-latest' }}
          run: |
            gh release upload ${{ github.event.inputs.release_tag }} src-tauri/target/release/bundle/deb/*.deb
            gh release upload ${{ github.event.inputs.release_tag }} src-tauri/target/release/bundle/rpm/*.rpm
            gh release upload ${{ github.event.inputs.release_tag }} src-tauri/target/release/bundle/appimage/*.AppImage
          env:
            GH_TOKEN: ${{ github.token }}

        - name: Release Windows
          if: ${{ matrix.os == 'windows-latest' }}
          run: |
            gh release upload ${{ github.event.inputs.release_tag }} src-tauri/target/release/bundle/msi/*.msi
          env:
            GH_TOKEN: ${{ github.token }}

        - name: Release macOS
          if: ${{ matrix.os == 'macos-latest' }}
          run: |
            gh release upload ${{ github.event.inputs.release_tag }} src-tauri/target/release/bundle/dmg/*.dmg
          env:
            GH_TOKEN: ${{ github.token }}

